<?php

namespace DiscussionBundle\Repository;

/**
 * BestAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BestAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
